### ISSUE TITLE
Error in creating sample, Template parameter JToken type is not valid

### ISSUE THREAD

**Issue by andreracz** [microsoft/fhir-server-samples#91] opened 2020-09-02 20:37 UTC
I'm trying to create the sample server for importing some test data, but I'm getting an error:

Here is the command I'm running:
`.\Create-FhirServerSamplesEnvironment.ps1 -EnvironmentName avfhir -UsePaaS $true`

And here is the output.
```
Current context is user: XXXXX
Current context is user: XXXXX
avfhir
FhirServer PS module is loaded
Creating keyvault with the name avfhir-ts
WARNING: Breaking changes in the cmdlet 'New-AzKeyVault' :
WARNING:  - The ability to create new key vaults with soft delete disabled will be deprecated by December 2020. All key
 vaults will be required to have soft delete enabled. Please see the following documentation for additional guidance.
https://docs.microsoft.com/azure/key-vault/general/soft-delete-change

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: The provided information does not map to an AD object id.
WARNING: Access policy is not set. No user or application have access permission to use this vault. This can happen if
the vault was created by a service principal. Please use Set-AzKeyVaultAccessPolicy to set access policies.
Current context is user: XXXXX
Current context is user: XXXXX
Adding permission to keyvault for bb81b944-1be0-4118-9c2c-3834a636cfb5
Ensuring API application exists
Checking if UserPrincipalName exists
User not, will create.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Set-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
WARNING: Breaking changes in the cmdlet 'Get-AzKeyVaultSecret' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING:  - "The output type 'Microsoft.Azure.Commands.KeyVault.Models.PSDeletedKeyVaultSecret' is changing"
 - The following properties in the output type are being deprecated :
 'SecretValueText'

WARNING: Note :The change is expected to take effect from the version :  '3.0.0'

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
New-AzResourceGroupDeployment : 5:30:34 PM - Error: Code=InvalidTemplate; Message=Deployment template validation
failed: 'Template parameter JToken type is not valid. Expected 'String, Uri'. Actual 'Object'. Please see
https://aka.ms/resource-manager-parameter-files for usage details.'.
At C:\dev\FHIR\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:187 char:1
+ New-AzResourceGroupDeployment -TemplateUri $sandboxTemplate -environm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

New-AzResourceGroupDeployment : The deployment validation failed
At C:\dev\FHIR\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:187 char:1
+ New-AzResourceGroupDeployment -TemplateUri $sandboxTemplate -environm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResourceGroupDeployment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

Warming up site...
Invoke-WebRequest : The remote name could not be resolved: 'avfhir.azurehealthcareapis.com'
At C:\dev\FHIR\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:190 char:1
+ Invoke-WebRequest -Uri "${fhirServerUrl}/metadata" | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Invoke-WebRequest : The remote name could not be resolved: 'avfhirimp.azurewebsites.net'
At C:\dev\FHIR\fhir-server-samples\deploy\scripts\Create-FhirServerSamplesEnvironment.ps1:192 char:1
+ Invoke-WebRequest -Uri $functionAppUrl | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand


Name                           Value
----                           -----
fhirServerUrl                  https://avfhir.azurehealthcareapis.com
dashboardUserPassword          WA;oA]XG%I>V!RzF
dashboardUserUpn               avfhir-admin@XXXXXXXX
dashboardUrl                   https://avfhirdash.azurewebsites.net
```

**Comment by ginalee-dotcom** [comment] 2020-09-03 00:40
There is a chance it failed because the resource name `avfhir` was taken. Currently we don't check for the environment before creating it, and wait till the end to do the actual creation. You can try removing what you deployed and then re-deploying using a more unique environment name.

**Comment by andreracz** [comment] 2020-09-03 11:22
I tried several different names, and all failed with the same error: 'Template parameter JToken type is not valid. Expected 'String, Uri'. Actual 'Object'

**Comment by hansenms** [comment] 2020-09-03 16:58
I don't think it is related to the name but I also cannot reproduce your problem. I just tried and managed to get the deployment running. I am using AzureAd version 2.0.2.4 and Az version 4.1.0.

What versions are you using? Are you in PowerShell or PowerShell Core? And which version?

**Comment by andreracz** [comment] 2020-09-03 21:12
I'm using powershell, version:

$PSVersionTable.PSVersion:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1

Az version 4.6.1 and AzureAd version 2.0.2.106

I'll try to downgrade Az to 4.1.0 and report here the result.

**Comment by andreracz** [comment] 2020-09-03 22:09
Downgrading the Az module to 4.1.0 worked. Thanks for the help.

**Comment by hansenms** [comment] 2020-09-03 22:55
@andreracz, thanks for working your way through that. @ginalee-dotcom, I think would make sense to work through what the issue is in the new version of the PS module and get an update to the template and/or scripts as needed. I would keep this issue open to track it.

**Comment by anniesingh** [comment] 2020-09-08 15:49
hi @andreracz, I am facing the same issue and trying the same solution of downgrading the Az module to version 4.1.0 which is currently 4.6.1 but it is giving me a downgrade error.
_Error:_
Install-Package: /opt/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:13067
 Line |
13067 |  …           $sid = PackageManagement\Install-Package @PSBoundParameters
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Unable to find repository 'https://www.poshtestgallery.com/api/v2'. Use Get-PSRepository to see all available repositories.

_command using to update Az version:_
`Update-Module -Name Az -RequiredVersion 4.1.0 -Force`

Could you please guide me on how to proceed?

**Comment by andreracz** [comment] 2020-09-08 17:59
@anniesingh , I uninstalled the module and installed the old version, following this guide:

https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-4.6.1#:~:text=set%20of%20instructions.-,Uninstall%20the%20Az%20PowerShell%20module%20from%20PowerShellGet,must%20uninstall%20each%20module%20individually.

**Comment by vigneshrajan5** [comment] 2020-09-09 12:58
@andreracz  - FYI: I ran into the same issue and downgraded my Az & AzureAd version to 4.1.0 & 2.0.2.106 per your comment but NO LUCK. The only discrepancy I see b/w you & I is the PS version (5.1.18362.752). Am I missing something? @hansenms - Thoughts? Any help in this regard would be appreciated... Look forward to hearing back. Thanks!!!

**Comment by cyberuna** [comment] 2020-09-11 19:29
Same error with Az & AzureAd version to 4.1.0 & 2.0.2.106.  @hansenms /  @ginalee-dotcom - Could you help?
![Error](https://user-images.githubusercontent.com/50457372/92965199-fb52a780-f43a-11ea-868a-b5469739527b.PNG)

**Comment by vigneshrajan5** [comment] 2020-09-13 10:18
FYI: I was able to get past the error by running the script on a VM with PS Version: 5.1..17763.1007 along with Az version: 4.1.0 & AzureAd version: 2.0.2.106. Seems like anything above this PS version, the script bombs out. Hope this helps. Thanks

**Comment by cyberuna** [comment] 2020-09-14 21:05
My colleague was able to do the same.  Run the script on a VM with PS Version: 5.1..17763.1007 along with Az version: 4.1.0 & AzureAd version: 2.0.2.106 and works. He has PS Version 5.1.19041.1 on his laptop. Does anyone know if the build matters and if it does how to get PS Version: 5.1..17763.1007?

**Comment by robwafle** [comment] 2020-09-21 17:45
I'm having the same problem.

`Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1`

**Comment by ginalee-dotcom** [comment] 2020-09-21 22:38
Hi all, we are looking into this - sorry for the delay. I will update you as soon as it is fixed.

**Comment by cyberuna** [comment] 2020-10-13 21:18
Any updates @ginalee-dotcom?

**Comment by ginalee-dotcom** [comment] 2020-11-29 04:28
Hi all, sorry for the delayed reply. **The new Az module requires PowerShell version 5.1 or above installed on your computer.** So if you have PowerShell version below 5.1, you need to update it. @robwafle So it should be deployable for you - and I believe @zxue helped you out with this.
A temporary way around this issue is to avoid using Az module version 4.6.1. **There is a bug with PowerShell Az Module version 4.6.1 confirmed with Azure ARM team. For now, please use version 4.5.0 (confirmed by myself today that it works fine), or versions 4.7.0 or above.** I am closing this issue and creating a new issue specifically for making this deployable on the majority of Az module versions, including 4.6.1 once that bug is fixed from the external team.

**Closed by ginalee-dotcom** 2020-11-29 04:28 UTC
Labels: help wanted
